# Generated by Django 2.2.7 on 2019-11-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
