# Generated by Django 2.2.7 on 2019-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='utils.Tag'),
        ),
    ]
