# Generated by Django 2.2.7 on 2019-11-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_address_user'),
        ('activities', '0002_auto_20191106_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='utils.Address'),
        ),
    ]
