# Generated by Django 2.2.7 on 2019-11-11 21:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupactivity',
            options={'verbose_name_plural': 'Group activities'},
        ),
        migrations.AlterModelOptions(
            name='individualactivity',
            options={'verbose_name_plural': 'Individual Activities'},
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='max_attendees',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
