# Generated by Django 2.2.7 on 2019-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20191111_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
