# Generated by Django 2.2.7 on 2019-11-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20191113_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='utils.Address'),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['title'], name='activities__title_903bfa_idx'),
        ),
    ]
